### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by KimetsuAndrea** [ShakirFarhan/Realtime-Chat#7]
What is the url means?

**Comment by KimetsuAndrea** [comment]
Error:

❯ npm start                                                                             
> server@1.0.0 start                                                                    > nodemon index.js

[nodemon] 3.1.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node index.js`
MongoDB - Connected
(node:16327) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server Listening at PORT - 8000
/data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongodb-connection-string-url/lib/index.js:86
            throw new MongoParseError('Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"');
                  ^

MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongodb/lib/connection_string.js:188:17)
    at new MongoClient (/data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongodb/lib/mongo_client.js:46:63)
    at /data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongoose/lib/connection.js:802:16
    at new Promise (<anonymous>)
    at Connection.openUri (/data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongoose/lib/connection.js:799:19)
    at /data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongoose/lib/index.js:414:10
    at /data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/data/data/com.termux/files/home/Realtime-Chat/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)

Node.js v23.4.0
[nodemon] app crashed - waiting for file changes before starting...
